name: deafabrax
channels:
  - defaults
dependencies:
  - python=3.10.12  # Specify the Python version you want to use
  - numpy=1.25.2
  - pandas=2.0.3
  - scikit-learn=1.2.2
  - lightgbm=4.1.0
  - flask=2.2.5
  - requests=2.26.0
  - matplotlib
  - seaborn
  - lightgbm=4.1.0
  - pytz
  - pip
  - pip:
    - ta
    - keras==2.15.0
    - tensorflow==2.15.0  
    - MetaTrader5
    - xgboost
